### ISSUE TITLE
practica 4 y 5 lectura y escritura  de un contrato inteligente

### ISSUE THREAD

**Issue by Rufino07** [SistemasTecTlaxiaco/actividad-8-practica-4y5-lectura-y-escritura-de-un-contrato-tecno-power-1#1]
[Practica 3-4 Lectura y escritura de un contrato inteligente .pdf](https://github.com/SistemasTecTlaxiaco/actividad-8-practica-4y5-lectura-y-escritura-de-un-contrato-tecno-power-1/files/15278267/Practica.3-4.Lectura.y.escritura.de.un.contrato.inteligente.pdf)

**Comment by josealfredo79** [comment]
Bien heccho y revisado...calificacion 19
